// generated by stringer -type=tokenType -output=token_string.go; DO NOT EDIT

package jcfg

import "fmt"

const _tokenType_name = "tokenErrortokenEOFtokenKeywordtokenValuetokenValueStringtokenEndStatementtokenSectionStarttokenSectionEndtokenLineCommenttokenHashCommenttokenBlockCommenttokenModifiertokenListStarttokenListEnd"

var _tokenType_index = [...]uint8{10, 18, 30, 40, 56, 73, 90, 105, 121, 137, 154, 167, 181, 193}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	hi := _tokenType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _tokenType_index[i-1]
	}
	return _tokenType_name[lo:hi]
}
